# Generated by Django 3.2.8 on 2021-11-06 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-listing', '-current_bid'), 'verbose_name_plural': 'Bids'},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='amount',
            new_name='current_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='history',
            field=models.ManyToManyField(related_name='bids', through='auctions.Bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
